name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
        - run: cd ..
        - run: pwd
        - run: ls
        - run: pip3 install -e . --no-deps
        - run: pytest-3